### ISSUE TITLE
New release please?

### ISSUE THREAD

**Issue by marcomorain** [drewr/postal#102]
Hit @drewr

Thank you for this library. We use it at CircleCI and it works great. 👏 

Could you make a new release of this library please? I'm trying to work around the issue that was fixed in #91 - but I'd rather pull in the upstream fix.

Thank you again.

Marc

**Comment by drewr** [comment]
`2.0.3` released, with [more proper CircleCI representation](https://circleci.com/gh/drewr/postal/tree/master) :smile: 

https://clojars.org/com.draines/postal

Thanks for your support!

**Comment by marcomorain** [comment]
Thank you! 👍👍
