### ISSUE TITLE
How to send own specific name while sending the email?

### ISSUE THREAD

**Issue by RomitGandhi07** [drewr/postal#110]
Eg: I'm sending an email using abc@gmail.com and I want that the recipient will receive the email by XYZ name but currently they are getting an email with name either abc or email id itself.

Is there any way to specify a specific name? @drewr

**Comment by dancek** [comment]
First, if you're trying to spoof the sending address, that is up to the SMTP server, not the client.

Second, it's bad manners to request help in other issues.

**Comment by RomitGandhi07** [comment]
@dancek Sorry for that, I deleted that comment.

 I'm not trying to spoof but the issue is my email id is demo@gmail.com and in the Gmail, I have set my name as ABC XYZ but in the recipient side it is displaying email address instead of name.

**Comment by dancek** [comment]
Does `ABC XYZ <demo@gmail.com>` work?

**Comment by RomitGandhi07** [comment]
```
(mail/send-message {:host "smtp.gmail.com"
                      :user "democera@gmail.com"
                      :pass "XXX"
                      :port 587
                      :tls true}
                     {:from "democera@gmail.com"
                      :to "XXX"
                      :subject "Final Demo"
                      :body [{:type "text/html"
                              :content "<font color=\"red\">Welcome</font>"}]})
```

This is the code that I have written, can you tell me where I should change?

**Comment by drewr** [comment]
You would use it with the `from:` key, for example: https://github.com/drewr/postal/blob/506072a314890f274c0d0921b05dbfa35e1b2665/test/postal/test/message.clj#L38

**Comment by dpsutton** [comment]
This was a helpful thread. I had thought the only way to accomplish this was to create an `InternetAddress` and use the constructor `InternetAddress(String address, String personal)`. I didn't realize the that you could use the form `Personal <email>`. And it does not seem like we can pass in an `InternetAddress` as the `from` this is a nice way to accomplish this. Thank you.
