### ISSUE TITLE
charset problem

### ISSUE THREAD

**Issue by wuzhe** [drewr/postal#5]
When I put unicode characters in subject line and message body, for the first a few messages it worked good, but subsequence messages were delivered with wrong charset:

Content-Type: text/plain; charset=ANSI_X3.4-1968

all unicode characters are showing as question marks.

**Comment by faywong** [comment]
I also observed this issue when i input some Chinese characters in subject or message body field.
(Note: my ContentType is intend to set to "text/plain" for investigate purpose)

![image](https://cloud.githubusercontent.com/assets/1934627/9765433/c8dad066-5746-11e5-8fe1-e6891366bad6.png)

 all unicode characters are showing as question marks.

**Comment by tsmacdonald** [comment]
I believe this is fixed by #95 (c.f. #94)

**Comment by drewr** [comment]
@tsmacdonald ❤️
