### ISSUE TITLE
Should "-f FROM" be "-f" "FROM" in sendmail invocation?

### ISSUE THREAD

**Issue by rlbdv** [drewr/postal#63]
I wondered why there was a (format "-f %s" ...) rather than something like ["-f" (sender msg)] here:

https://github.com/drewr/postal/blob/4b445ef606f1bdeab832a7179595a41832be3edb/src/postal/sendmail.clj#L72

Though I'm not as famliar with ProcessBuilder as with clojure.java.shell/sh, etc., it looks like with the current code, sendmail may be receiving the space as part of the from address.

**Comment by drewr** [comment]
Nope, that's a bug! Thanks!

**Comment by rlbdv** [comment]
Drew Raines <notifications@github.com> writes:

> Nope, that's a bug! Thanks!

Certainly, and I don't know if it's intentional, but it looks like
maybe you don't have anything after 1.11.0 tagged on github.

-- 
Rob Browning
rlb @defaultvalue.org and @debian.org
GPG as of 2011-07-10 E6A9 DA3C C9FD 1FF8 C676 D2C4 C0F0 39E9 ED1B 597A
GPG as of 2002-11-03 14DD 432F AE39 534D B592 F9A0 25C8 D377 8C7E 73A4
