### ISSUE TITLE
Bump javax.mail/mail dep to 1.5.4

### ISSUE THREAD

**Issue by cstrahan** [drewr/postal#69]
Would it be possible to bump the dependency on `javax.mail/mail` to version 1.5.4, please? For example, `io.forward/clojure-mail` is already using it.

**Comment by drewr** [comment]
It is totally possible!  I need to do a new release soon, and will include it.

**Comment by cstrahan** [comment]
Cool - thanks, @drewr!

**Comment by gsnewmark** [comment]
Is new release still planned?

**Comment by drewr** [comment]
Sorry for the delay, `2.0.0` is out with JavaMail 1.5.5.
