### ISSUE TITLE
Requesting change log for v2?

### ISSUE THREAD

**Issue by ptaoussanis** [drewr/postal#74]
Hi Drew,

I notice that the [CHANGES](https://github.com/drewr/postal/blob/master/CHANGES) file hasn't been updated for `[com.draines/postal "2.0.0"]` yet. Any chance we could request an update? Are there any breaking changes?

Thanks a lot! (And a big thanks for your great work on Postal).

Cheers :-)

**Comment by drewr** [comment]
Sorry about that!  It was mostly fixing a project governance issue with branching, but there were a few things I forgot to backport to 1.x.  Found those things and added some notes in 
df8f4328b57e224d57ed9ebd6d877cbc8d64b4f4.

Thanks Peter!

**Comment by ptaoussanis** [comment]
No problem Drew. So just to confirm: users of 1.11.4 can swap in 2.0.0 without any expected breaks?

Cheers :-)

**Comment by drewr** [comment]
Yes, that's hopefully the case :+1:
